name: dart_eval
description: A flexible Dart interpreter written in Dart, enabling code push for AOT Dart apps.
# version: 0.0.1
# homepage: https://github.com/ethanblake4/dart_eval

environment:
  sdk: '>=2.12.0-21.0.dev <3.0.0'

dependencies:
   analyzer:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
