name: iona_flutter
description: A code editor built in Flutter.

environment:
  sdk: '>=2.9.0-18.0.dev <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  analysis_server_lib:
  built_value:
  built_collection:
  scoped_model: ^1.0.1
  event_bus: ^1.1.0
  flutter_screenutil:
  pedantic:
  sembast:
  isolate:
  yaml:
  equatable:
  piecemeal: any
  cupertino_icons: ^0.1.0
  analyzer:
  selection_menu: ^0.9.0
  ffi_terminal:
    path: /Users/ethanelshyeb/ffi_terminal
  devtools_app:
    path: ../devtools/packages/devtools_app


  # Desktop embedder plugins.
  # Note: In an actual project, these paths would include the
  # path from your application to the flutter_desktop_embedding
  # checkout.
  color_panel:
    path: ../plugins/color_panel
  file_chooser:
    path: ../plugins/file_chooser
  menubar:
    path: ../plugins/menubar
  window_size:
    path: ../plugins/window_size
  path_provider: ^1.6.5
  path_provider_fde:
    path: ../plugins/flutter_plugins/path_provider_fde
  shared_preferences: ^0.5.6
  url_launcher: ^5.4.0
  url_launcher_fde:
    path: ../plugins/flutter_plugins/url_launcher_fde

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - nativeLibs/libvterm.dylib
    - nativeLibs/libvterm.0.dylib
    - nativeLibs/libvterm.a
    - nativeLibs/libvterm.lai
    - assets/icons/dart.png

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900

    - family: OfficeCodePro
      fonts:
        - asset: fonts/OfficeCodePro/OfficeCodePro-Light.otf
          weight: 300
        - asset: fonts/OfficeCodePro/OfficeCodePro-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/OfficeCodePro/OfficeCodePro-Regular.otf
          weight: 400
        - asset: fonts/OfficeCodePro/OfficeCodePro-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/OfficeCodePro/OfficeCodePro-Medium.otf
          weight: 500
        - asset: fonts/OfficeCodePro/OfficeCodePro-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/OfficeCodePro/OfficeCodePro-Bold.otf
          weight: 700
        - asset: fonts/OfficeCodePro/OfficeCodePro-BoldItalic.otf
          weight: 700
          style: italic
    - family: Hack
      fonts:
        - asset: fonts/Hack/Hack-Regular.ttf
          weight: 400
        - asset: fonts/Hack/Hack-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Hack/Hack-Bold.ttf
          weight: 700
        - asset: fonts/Hack/Hack-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Cascadia
      fonts:
        - asset: fonts/Cascadia/CascadiaMono.ttf
